global:
  resolve_timeout: 5m
route:
  group_by: ['example']
  #group_wait:#
  #group_interval:#
  #repeat_interval:#
  receiver: 'email'
receivers:
- name: 'email'
  email_configs:
  #- to:#
    #from:#
    #smarthost:#:#smarthost_port#
    #require_tls:#
    #auth_username:#
    #auth_identity:#
    #auth_password:#
    headers:
      #subject:#
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
